<a href="https://colab.research.google.com/github/shariq101/Understanding-Keras-Layers/blob/main/Convolution1D_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Understanding tf.keras Layers
import tensorflow as tf
import numpy as np
print('Tensorflow ',tf.__version__)
print('Tensorflow.Keras ',tf.keras.__version__)

Tensorflow  2.11.0
Tensorflow.Keras  2.11.0


According to Keras documentation:

This layer creates a convolution kernel that is convolved with the layer input over a single spatial (or temporal) dimension to produce a tensor of outputs.

If use_bias is True, a bias vector is created and added to the outputs. Finally, if activation is not None, it is applied to the outputs as well.

When using this layer as the first layer in a model, provide an input_shape argument (tuple of integers or None, e.g. (10, 128) for sequences of 10 vectors of 128-dimensional vectors, or (None, 128) for variable-length sequences of 128-dimensional vectors.

In [2]:
import tensorflow as tf
import numpy as np

# The inputs are 128-length vectors with 10 timesteps, and the batch size  
# is 4.  
input_shape = (4, 10, 128)
x = tf.random.normal(input_shape)
print('x.shape: ', x.shape)
print('input shape parameter value to Conv1D: ', input_shape[1:])
y = tf.keras.layers.Conv1D(32, 3, activation='relu',input_shape=input_shape[1:])(x)
print('y.shape: ',y.shape)

x.shape:  (4, 10, 128)
input shape parameter value to Conv1D:  (10, 128)
y.shape:  (4, 8, 32)


In [3]:
print('y:\n',y)

y:
 tf.Tensor(
[[[1.4143059  2.9352179  0.         ... 0.         0.3062138  2.9548986 ]
  [0.02409244 0.         1.461117   ... 0.16552728 0.9900678  0.        ]
  [1.2701575  0.14964044 0.9087007  ... 0.5257775  0.26845858 0.        ]
  ...
  [2.445037   0.         0.7077065  ... 0.         0.49014455 0.32760826]
  [0.         0.         0.16434747 ... 0.45763326 0.         0.9310955 ]
  [0.         0.         0.         ... 0.         0.         1.9681315 ]]

 [[0.57109183 1.5129019  1.4104242  ... 0.         0.6144254  0.        ]
  [0.         2.0601132  0.3226842  ... 0.         1.70277    0.        ]
  [1.6416994  0.         2.9030936  ... 0.         0.         0.        ]
  ...
  [0.         1.4941611  0.         ... 1.6155776  0.45449    0.        ]
  [0.04212806 0.6330142  0.         ... 1.4666636  0.         0.81801736]
  [0.         0.         0.46263143 ... 2.3388166  0.7906592  0.        ]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.  

In [4]:
course= 4
section= 3
student = 5 
input_shape = (course,section, student)

grades = np.random.uniform(size=input_shape,high=100)

print('grades.shape: ', grades.shape)
print('grades:\n', grades)


grades.shape:  (4, 3, 5)
grades:
 [[[54.10102531 87.76283499 69.71397659 18.43269867  4.79861394]
  [ 8.10294397 16.89416607 59.34308531 99.22916015 45.62429002]
  [16.57888473 82.9462677  39.70461441 78.96019105 15.60278642]]

 [[77.48544295 49.58622656 89.22647635 57.96622315 60.00191548]
  [25.54564262  8.00743371  3.70105802 21.17277892 67.04117751]
  [15.56623695 28.63276776 97.21736346 65.03523739 87.82110157]]

 [[99.18627932 63.76467406 41.96971597 66.38254417 49.3426827 ]
  [ 3.27419318 61.4584089  74.486658   49.74914215 51.62705618]
  [61.5534843  56.45908568 25.62854586 63.70587771 31.25330856]]

 [[65.63919887 49.21447421 79.61995768 51.94434409  6.27953296]
  [72.10632661 64.20660479 70.08730904  5.2420871  60.06937265]
  [30.99103815 87.57497556 19.61343695 31.37728371  8.44204598]]]


In [5]:
print(grades[0].sum(), grades[1].sum(), grades[2].sum(), grades[3].sum())

697.7955393116115 754.0070823945143 799.8416567337022 702.4079883454435


However, think about 1D convolution which applies a filter whose all weights are one and bias is 0 to the input

Remeber how NN computes output without any activation function: Wx+b

Then the result will be sum of the values in x provided that kernel_size covers all the sections (rows) in x.

In other words, if input shape is [a,b,c] kernel_size must be equal to b.

Because kernel size determines how many rows should be handled by the filter at once!

Remember 1D: we take care into all the columns!

In [8]:
print('input shape parameter value to Conv1D: ', input_shape[1:])
inputs = tf.keras.Input(shape=input_shape[1:])

kernelSize= section
print('kernelSize: ', kernelSize)

outputs = tf.keras.layers.Conv1D(1, kernelSize)(inputs)
print('output shape of the Conv1D : ',outputs.shape)

model=tf.keras.Model(inputs, outputs)
model.compile(
    loss="binary_crossentropy",
    metrics=["accuracy"],
)
print(model.summary())

input shape parameter value to Conv1D:  (3, 5)
kernelSize:  3
output shape of the Conv1D :  (None, 1, 1)
Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 3, 5)]            0         
                                                                 
 conv1d_2 (Conv1D)           (None, 1, 1)              16        
                                                                 
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
# prepare a filter such that
# W is all ones
# b is zero
myWeights=(np.ones((kernelSize,student,1)), np.zeros(1,))
model.get_layer(index=1).set_weights(myWeights)

In [10]:
model.predict(grades.reshape(-1,section,student))

1/1 [==============================] - 0s 320ms/step


array([[[697.79553]],

       [[754.00714]],

       [[799.8416 ]],

       [[702.40796]]], dtype=float32)