<a href="https://colab.research.google.com/github/shariq101/Understanding-Keras-Layers/blob/main/Global_Max_Pooling_1D_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Understanding tf.keras Layers
import tensorflow as tf
import numpy as np
print('Tensorflow ',tf.__version__)
print('Tensorflow.Keras ',tf.keras.__version__)

Tensorflow  2.11.0
Tensorflow.Keras  2.11.0


In this tutorial, we will try to understand one of the layers provide by Keras.
#Global Max Pooling 1D Layer

As per the documentation provided by Keras. The layer can be described as :-


1.   Global Max Pooling operation works for ID Temporal Data.
2.   Downsamples the input representation by taking the maximum value over the time dimension.



Now to uderstand the Time dimension/ Temporal Data, lets consider an example:-

Consider a Satellite on a planet taking 3 measurements:- Surface Temperature, Pressure and Humidity of a planet, twice a day

In [2]:
morning= [18, 150, 76]
evening = [25, 140, 88]
firstDay= [morning,evening]
print('Two observations from the First Day of 3 sensor-data: \n', firstDay)

Two observations from the First Day of 3 sensor-data: 
 [[18, 150, 76], [25, 140, 88]]


###Day 2 

The following observations were taken:-

In [3]:
firstDay= [[18, 150, 76], [25, 140, 88]]
secondDay= [[19, 160, 76], [29, 140, 68]]
log = firstDay+secondDay
print('2 days observations:\n',log)


2 days observations:
 [[18, 150, 76], [25, 140, 88], [19, 160, 76], [29, 140, 68]]


convert the list to np array with proper shape for 2 days, 2 observations of 3 sensors:

In [4]:
log= np.array(log).reshape(2,2,3)
print(log)

[[[ 18 150  76]
  [ 25 140  88]]

 [[ 19 160  76]
  [ 29 140  68]]]


In [5]:
print(log.shape)

(2, 2, 3)


In [6]:
log = tf.constant(log)
print('Input Log: \n', log)
max_pool_1d = tf.keras.layers.GlobalMaxPooling1D()
max_values_per_day= max_pool_1d(log)
print('\nmax_values_per_day\n',max_values_per_day)

Input Log: 
 tf.Tensor(
[[[ 18 150  76]
  [ 25 140  88]]

 [[ 19 160  76]
  [ 29 140  68]]], shape=(2, 2, 3), dtype=int64)

max_values_per_day
 tf.Tensor(
[[ 25 150  88]
 [ 29 160  76]], shape=(2, 3), dtype=int64)


Two understand the ouput, we have to understand the shape of input tensor.
Lets consider the shape of the input as (p,q,r), where


*   p represents the samples taken. In this example it will be measurements per day.
*   q represents the time. The number of time measurement is taken in a day.
*   s represents the different quantity measured.

So when we apply Global Max Pooling, the readings are averaged in time dimension and time dimension is omitted in final output.




